
# static path
static="./static"

# ngrok authtoken
[ngrok]
use=false
auth=""

# production
[prd]
port=80
[prd.logging]
to_console=true
to_dump=true

# development
[dev]
port=1234
[dev.logging]
to_console=true
to_dump=false

